export { LoginPage } from './Login/index'
export { RegisterPage } from './Registration/index'
export { ChatPage } from './Chat'
export { ProfilePage } from './Profile'
export { ErrorPage } from './Error'
export { PasswordSettingPage } from './ProfileSettingPassword'
export { NotFoundPage } from './NotFound'
